---
title: "MoneyBall"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(highcharter) # Need to do more research on this subject
```

```{r}
Appearances <- read.csv("Baseball_Index/Appearances.csv")
Master <- read_csv("Baseball_Index/Master.csv")
Batting <- read_csv("Baseball_Index/Batting.csv")
Pitching <- read_csv("Baseball_Index/Pitching.csv")
Fielding <- read_csv("Baseball_Index/Fielding.csv")
Teams <- read_csv("Baseball_Index/Teams.csv")
AllStar <- read_csv("Baseball_Index/AllstarFull.csv")
Salaries <- read_csv("Baseball_Index/Salaries.csv")
Teams <- read_csv("Baseball_Index/Teams.csv")
```

```{r}
Appearances_df <-filter(Appearances, yearID == 2012, 2013, 2014, 2015, 2016)
Batting_df <-filter(Batting, yearID == 2012, 2013, 2014, 2015, 2016)
Pitching_df <- filter(Pitching, yearID == 2012, 2013, 2014, 2015, 2016)
Fielding_df <- filter(Fielding, yearID == 2012, 2013, 2014, 2015, 2016 )
Teams_df <- filter(Teams, yearID == 2012, 2013, 2014, 2015, 2016)
AllStar_df <- filter(AllStar, yearID == 2012, 2013, 2014, 2015, 2016)
Teams_df <- filter(Teams, yearID == 2012, 2013, 2014, 2015, 2016)
Salaries_df <- filter(Salaries, yearID == 2012, 2013, 2014, 2015, 2016)
```


```{r}
library(highcharter)
hchart(Batting_df, "scatter", hcaes(x = RBI, y = R, group = teamID) )
```



```{r}
ggplot(data = Batting_df) +
  geom_point(mapping = aes(x= RBI, y = R, color = teamID)) 

```


```{r}
filter(Batting_df, H > 200)
```



```{r}
# Data set focusing on batting, pitching and fielding
PlayBall <- left_join(Batting_df,Pitching_df, Fielding_df, by="playerID")
View(PlayBall)
```

```{r}
Other <- left_join(AllStar_df, Appearances_df, Salaries_df, by="yearID")
View(Other)
```


```{r}
MasterList <- left_join(PlayBall, Other, by="GS")
```


```{r}
PlayBall <- mutate(PlayBall, G = G.x + G.y) 
```

```{r}
reduce(PlayBall, intersect)

```

As you would expect, there is a positive linear relationship between at bats and RBI's. Similiar results with the other variables in this data set as well. 
```{r}
# Add jitter feature to spread out points
ggplot(data = PlayBall, mapping = aes(x = AB, y = RBI)) +
  geom_smooth() +
  geom_point() +
  geom_jitter() 
```

Interesting chart that shows how many games most players play.
```{r}
# Basic barplot in ggplot
ggplot(data = Pitching_df) +
  geom_bar(mapping = aes(x=G, color='blue'))
```

```{r}
# Use of statistical transformation in this code
# Not helpful here, but could have future use
ggplot(data = Batting_df) +
  stat_summary(
    mapping = aes(x = AB, y = RBI),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```
















